### ISSUE TITLE
Микс русского и английского языка

### ISSUE THREAD

**Issue by SimonOsipov** [tlbootcamp/tlroadmap#11]
Имеет ли смысл заменить направления русскими названиями, чтобы не миксовать? Вместо `Resource Manager` - `Управление ресурсами`, вместо `Administrator` - `Административные вопросы`?

**Comment by pavelpy** [comment]
Возможность автоматической замены русскими аналогами реализована тулзе #7 
Ждём принятия pull request'a

**Comment by etolstoy** [comment]
Вот не везде есть хорошие русские альтернативы. В названиях ролей хочется видеть именно обозначение роли, а не действия. Не "администрирование", а "администратор".

Ну и штуки вроде code review, one-to-one – разве надо переводить?

**Comment by antonkhvorov** [comment]
Мне кажется терминологию лучше оставлять оригинальную, т.е. английскую.

**Comment by etolstoy** [comment]
Обсудили с @DevAlloy . Кажется, все слепо сводить к русскому языку нет смысла. Если есть мысли по конкретным пунктам – давайте на них отдельно смотреть.

**Comment by ellited** [comment]
А планируется ли перевод схемы на английский?
