### ISSUE TITLE
Организовать CI

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#112]
Довольно быстро накопились разные проверки и скрипты, которые нужно дергать при каждом мердже:
- Проверка правописания
- Перегенерация базы знаний по майндмепу
- Висит PR про ньюлайны

Было бы круто наладить нормальный CI, чтобы оно вот само работало.

**Comment by timmson** [comment]
Попробовал yaspeller в Travis CI - https://travis-ci.org/timmson/tlroadmap/jobs/576285307.

**Comment by etolstoy** [comment]
Думаю да – уже пролезают PR с ошибками. Туда же и генерацию README.

**Comment by timmson** [comment]
Кину следующий PR спеллеру, а потом докручу генератор.  Обрытный пуш после генерации можно так положить - https://gist.github.com/willprice/e07efd73fb7f13f917ea, а ключик просписать в переменных окружения билд плана, чтобы был доступен только авторам репозитория

**Comment by etolstoy** [comment]
@timmson еще стоит добавить логику отсюда - https://github.com/tlbootcamp/tlroadmap/pull/111

**Comment by timmson** [comment]
> @timmson еще стоит добавить логику отсюда - #111

Если я все правильно сделал, то получается как-то так - https://travis-ci.org/timmson/tlroadmap/builds/578031320

**Comment by etolstoy** [comment]
Топ, кажется что да. Надо только перед запуском поправить ошибки найденные.

**Comment by DevAlloy** [comment]
Еще надо бы запускать генерацию ссылок из links.json и проверять, что автор PR уже сам прогнал скрипт.

**Comment by vvscode** [comment]
@timmson  сделаешь PR или этот таск свободен?

**Comment by timmson** [comment]
@vvscode, забирай. Я уже накидал конфигу для tavis ci, можно ее взять за основу - [https://github.com/timmson/tlroadmap/blob/ci/.travis.yml](https://github.com/timmson/tlroadmap/blob/ci/.travis.yml)

**Comment by vvscode** [comment]
@etolstoy  как на счет добавления `package.json` в проект? 

1) там можно описать команды для проверки репо
2) там можно описать `lint-staged` хуки для проверки перед коммитом

**Comment by vvscode** [comment]
Плюс - мы добавляем линтинг, нам бы в секции README.md или в файле CONTRIBUTION.md добавить описание этих проверок

мне это в том же PR сделать? или в отдельном?

**Comment by vvscode** [comment]
И в догонку - в python используется `lxml`, но никакого `requirement.txt` я не вижу ))

Как на счет переписать все на js? ;)

**Comment by etolstoy** [comment]
@vvscode eyo странно работает, предлагает заменять "чем конкретно хотите" на "чём конкретно хотите". Как сделать его менее геморройным, чем вручную настраивать исключения для таких случаев? :)

**Comment by etolstoy** [comment]
Вообще я за то, чтобы использовать один язык в репозитории. На питоне сейчас написан довольно большой кусок логики по синхронизации базы знаний и майндмепа. Что мы получим от переписывания его на js?

**Comment by vvscode** [comment]
@etolstoy  
1) про eyo - есть флаг `--only-safe` 
2) про js  - вы никаких бонусов не получите )) я просто уточнил, потому что ci сейчас на js настроен, а к python коду нет файла зависимостей - это я поправлю. Просто уточнил, что будем использовать - разницы для меня нет

**Comment by etolstoy** [comment]
Кажется, подняли.
