### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by loxp** [tlbootcamp/tlroadmap#117]
Hello, is there any plan of English version of this project?

**Comment by etolstoy** [comment]
Hi! Not at the moment, I think. Maybe when we'll finish the knowledge base in russian, we'll do some kind of crowdfunding to hire a professional translator.

**Comment by Gaket** [comment]
Hi! I'll prepare a translation of the Readme Page, so people will at least better understand what's the project is about overall.

**Comment by oleggromov** [comment]
Hello, folks, I was thinking of translating the mind map itself first, which shall be pretty trivial. 

The rest is trickier because it's much more information and text but again, if we manage to gain attention from the English-speaking community, it may be also translated by bi-lingual contributors.

**Comment by unicast** [comment]
Do we already know how to ensure constancy of translations?

**Comment by Gaket** [comment]
@unicast, let's discuss it here:
https://github.com/tlbootcamp/tlroadmap/pull/141

**Comment by alxnorden** [comment]
Do I understand correctly that the process has Russian as the default language and any future translations will branch from there? I.e  is it seen to be  of no benefit to the project to have an English translated map now? 
I can contribute translation as a native bi-lingual, but not sure if this is something the project needs at this time.
Хотелось бы уточнить - проект выбрал русский язык основным, на данный момент перевод и/или переход на английский не актуальны?
Могу  участвовать в проекте переводчиком как носитель обоих языков.

**Comment by etolstoy** [comment]
We discussed this issue with @DevAlloy and decided to temporarily stop all the attempts to translate the roadmap. We plan to finish the content in russian first, and then switch to translating.
