### ISSUE TITLE
Дополнение раздела "Собеседование/обратная связь"

### ISSUE THREAD

**Issue by tummma** [tlbootcamp/tlroadmap#119]
В разделе про обратную связь после собеседования ничего не сказано про то, что нужно обязательно ответить кандидату после собеседование и не особо важно положительный будет ответ или нет. После собеседование некоторые компании (в том числе и довольно крупные) перестают выходить на связь и начинают просто игнорировать кандидата.

**Comment by etolstoy** [comment]
Согласен, хорошо бы это добавить. Получится закинуть PR?

**Comment by tummma** [comment]
Я попытаюсь красиво это сформулировать и создам pr. Стоит ли указывать, что это должно работать в обе стороны, то есть кандидат тоже не должен бегать от компании и отвечать во время?

**Comment by etolstoy** [comment]
Наверное нет – все-таки это материал для тимлида, а не для кандидата.
