### ISSUE TITLE
Выбрать и добавить лицензию для проекта

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#123]
Нужно посмотреть, подходит ли нам дефолтная Creative Commons и добавить информацию в проект.
@DevAlloy что думаешь?

**Comment by etolstoy** [comment]
Кажется, нам норм подойдет [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). 

> Эта лицензия позволяет другим распространять, редактировать, поправлять и брать за основу ваше произведение, даже коммерчески, до тех пор пока они указывают ваше авторство. Это самая разрешительная из предлагаемых лицензий. Рекомендована для максимального распространения и использования лицензированных материалов.

**Comment by dector** [comment]
Я бы предложил [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) поскольку считаю `Share Alike` стратегию более выиграшной в данном случае.

**Comment by etolstoy** [comment]
А почему? Я не очень понял из описания, чем дополнительные условия по сохранению модели лицензирования лучше.

**Comment by dector** [comment]
@etolstoy Отличие только одно: добавление copy-left требования, суть которого в том, чтобы обеспечить доступность производного контента для сообщества.

СС BY-SA предыдущей версии, например, используется для статей на [Wikipedia](https://creativecommons.org/2009/06/22/wikipedia-cc-by-sa-free-culture-win/) или большинства контента на [Khan Academy](https://khanacademy.zendesk.com/hc/en-us/articles/202262954-Can-I-use-Khan-Academy-s-videos-name-materials-link-on-my-site-).
