### ISSUE TITLE
Добавление ветки "Развитие себя/Личный бренд"

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#124]
Мы тут с @DevAlloy кратенько обсудили, что, кажется, нужно такую ветку добавлять. Мотивация тут такая – прокачанный личный бренд помогает руководителю набирать себе команду и удерживать существующую. Плюс дает бонус к нетворкингу, который я как раз запуллреквестил (#122).

Что думаете?

**Comment by DevAlloy** [comment]
Да, я бы персональный бренд считал одним из подпунктов листочка «Развитие технического бренда», потому что это лишь один из возможных вариантов.

**Comment by etolstoy** [comment]
Мне кажется, что это все-таки в области персональных навыков, а не рабочих. Проверка – личный бренд останется с тобой при смене команды и компании, а инвестиции, вложенные в развитие техбренда компании – нет.
