### ISSUE TITLE
Personal skills

### ISSUE THREAD

**Issue by Barbatosso** [tlbootcamp/tlroadmap#14]
Авторы очень хорошо раскрыли `TeamLead roadmap`, но как-то совсем прошли мимо `personal skills`, упомянув их вскользь, хотя на 100% уверен, что есть о чем рассказать.

Пожалуйста, добавьте какие-то ресурсы и материалы по `personal skills` в дополнение к `roadmap`.

**Comment by etolstoy** [comment]
Там пусто как и во всех ветках кроме Resource Manager не потому, что мы считаем их не важными, а потому, что просто не успели сделать все :)

Тикет закрываю, так как это и так в планах – сами в какой-то момент доберемся, но если готов помочь по каким-то веткам, то присылай PR.
