### ISSUE TITLE
Добавление стилей лидерства

### ISSUE THREAD

**Issue by antonkhvorov** [tlbootcamp/tlroadmap#15]
За основу предлагаю взять статью HBR — Leadership That Gets Results (by Daniel Goleman)
В ней расписано 6 стилей лидерства и объясняется почему каждый лидер должен уметь применять соответствующий стиль в зависимости от условий.
http://www.powerelectronics.ac.uk/documents/leadership-that-gets-results.pdf

Стили:
1.  Coercive (Do what I tell you)
2. Authoritative (Come with me)
3. Affiliative (People comes first)
4. Democratic (What do you think?)
5. Pacesetting (Do as I do, now)
6. Coaching (Try this)

**Comment by etolstoy** [comment]
Забрал почитать, после этого отпишусь.

**Comment by antonkhvorov** [comment]
@DevAlloy можем списаться/созвониться для обсуждения, если захочешь.

**Comment by DevAlloy** [comment]
> @DevAlloy можем списаться/созвониться для обсуждения, если захочешь.

@antonkhvorov, ознакомлюсь в ближайшее время

**Comment by DevAlloy** [comment]
@antonkhvorov 
Пробежался по документу, про стили лидерства есть еще варианты:
- https://medium.com/@jurgenappelo/the-7-levels-of-delegation-672ec2a48103
- https://zillion.net/ru/blog/539/situatsionnoie-lidierstvo-4-stilia-rukovodstva-i-4-stiepieni-razvitiia-sotrudnikov
- Есть 4 веточки лидерства Адизеса, кажется, что нам немного под другим углом смотрят на руководителей

Как вариант, можно описать разные модели, затрагивая основную идею и на чем эта модель делает фокус.

**Comment by DevAlloy** [comment]
Чтобы еще не потерять: https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_X_%D0%B8_%D1%82%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_Y

**Comment by etolstoy** [comment]
Тут никакого движения очень давно нет, сам тикет закрою.
