### ISSUE TITLE
Описать ветку "Нефункциональные требования"

### ISSUE THREAD

**Issue by antonkhvorov** [tlbootcamp/tlroadmap#17]
В чате поступило предложение на добавление Информационной Безопасности в компетенции тим лида. Это важный атрибут качества, однако, не единственный, поэтому при добавлении инфобеза желательно добавить и другие атрибуты качества для того, чтобы покрыть весь спекрт контроля качества продукта.

В моем понимании тим лид должен мониторить атрибуты качества (например, [с помощью QAS](http://etutorials.org/Programming/Software+architecture+in+practice,+second+edition/Part+Two+Creating+an+Architecture/Chapter+4.+Understanding+Quality+Attributes/4.4+Quality+Attribute+Scenarios+in+Practice/). По поводу других активностей и их упоминание в роадмапе (например, задизайнить приложение (Usability), сделать пен-тест (Security) и т.д.) — вопрос спорный, мне кажется, что мы не должны для каждого из этих атрибутов расписывать такие вещи. Достаточно их декомпозиции для того, чтобы было понимание, что они существуют и что за ними нужно следить. 

Technical Lead —> Обеспечения качества продукта —> Нефункциональные требования —> [quality_attribute]

Нужно помнить, что в разных источниках по-разному определяют то, что стоит за атрибутами качества, соответственно, это влияет и на полноту коллекции. Поэтому предлагаю два сета, которые чаще всего встречаю в индустрии:
1) ISO 25010 [(кратко)](https://iso25000.com/index.php/en/iso-25000-standards/iso-25010) [(подробно)](https://www.iso.org/obp/ui/#iso:std:iso-iec:25010:ed-1:v1:en)
- Functional Suitability
- Performance Efficiency
- Compatibility
- Usability
- Reliability
- Security
- Maintainability
- Portability

2) Книга Software Architecture in Practice (в народе BCK) — Len Bass, Paul Clements, Rick Kazman (3rd edition)
- Availability
- Interoperability
- Modifiability
- Performance
- Security
- Testability
- Usability
примечание: эти атрибуты там подробно расписаны, в том числе и как их трекать. Однако, там упоминаются и другие, превращая список в более объемный

**Comment by etolstoy** [comment]
Посмотрел – мне нравится такой подход. Вопрос в том, как конкретно это в Technical Lead вложить – в ветку `Качество продукта`, или в подветку `Нефункциональные требования` или вообще сбоку качества продукта вывести?

**Comment by antonkhvorov** [comment]
Думаю лучше в подветку `Нефункциональные требования`, это дает понимание тим лиду, что такое атрибуты качества и какие они бывают. Все это находится в ветке `Обеспечение качества продукта`, поэтому думаю ветка `Качество продукта` уже будет избыточна в этом случае.
Надо посмотреть как пойдет, какие вопросы будут задавать. В моем виденье в дальнейших статьях будет описываться то, как следить за этими атрибутами с помощью метрик (приводил уже пример с QAS) и какие активности связаны с тем или иными атрибутам.

Так же готов описать эти разделы, потому что тема всегда была интересна мне. Через призму атрибутов качества всегда интересно смотреть на продукты и сравнивать их друг с другом. Я думаю, что это полезный скилл для тим лида.

**Comment by etolstoy** [comment]
Обсудили с @DevAlloy. Выглядит хорошо, нам ближе наверное вариант с `Software Architecture in Practice` - навскидку кажется, что он ближе к реальности чем `ISO`. Предлагаю так поступить:
1. Закинем issue в чатик, соберем больше мнений.
2. С выбранным вариантом @antonkhvorov закинет PR в роадмап.

**Comment by antonkhvorov** [comment]
@etolstoy @DevAlloy а другие атрибуты качества смотрели, которые приводятся в `Software Architecture in Practice`? Там подробно расписаны те, что я привел выше, а так же есть упоминания и про другие, они там отдельной главой идут.

Так же да, все верно — это лишь два примера из классификаций качества продукта. Будет интересно услышать, кто какие применяет у себя на практике.

**Comment by etolstoy** [comment]
Пока что описал в PR #203 именно как нефункциональные требования. В будущем можем поправить и доработать.
