### ISSUE TITLE
Resource Manager -> People Manager

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#178]
Кажется, нам стоит переименовать ветку Resource Manager в People Manager. Почему:
- Технически, ресурсы – это не только человеческий труд, но и, к примеру, финансы. В нашей же ветке присутствуют только люди.
- People manager звучит не так галерно.

Что думаете?

**Comment by antonkhvorov** [comment]
У нас если говорится про проект, то resources это всегда про выделенных на него людей. Если говорить про всякие траты на серваки, тулзы и прочие косы — это budjet
People management это скорее одна из ее веток (как и есть в роадмапе, Управление людьми), про менторство, обратную связь и вот это всё.
Так что мне видится что не нужно переименовывать

**Comment by etolstoy** [comment]
Обсудили со Стасом, переименовываем.
