### ISSUE TITLE
Where to put translated files?

### ISSUE THREAD

**Issue by rokr97** [tlbootcamp/tlroadmap#184]
I want to contribute in translation to English and I don't understand where to place translated files. Yes, there's `translations` folder but it's structure is not described. Moreover if we are to put translated files there it will be a chore to update links in roadmap and readme files.

So I propose to add explicit `ru-ru` suffix to all existing `md`-files written in Russian and add explicit `[RU]` tag to all link names in translated roadmap (TBD) and readme.
This way making a translation and updating the links will be straightworward. Let's see an example of the flow when we want to translate `skills/resource-manager/delegation.md` to English:

1. clone the `tlroadmap/skills/resource-manager/delegation-ru-ru.md`
2. rename it to `tlroadmap/skills/resource-manager/delegation-en-us.md`
3. do the translation
4. open `tlroadmap/README-en-us.md` and `tlroadmap/roadmap-en-us.puml` and change 
`[Delegation (RU)](https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/delegation-ru-ru.md)` link to 
`[Delegation (EN)](https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/delegation-en-us.md)`

This way it will be explicitly visible in README and roadmap which parts are already translated and worth clicking by non-RU users.

Further, the same flow could be applied if someone is willing to translate English version to Simple Chinese or Brasilian Portuguese or any other language.

**Comment by etolstoy** [comment]
Well, we still didn't started the translation process :( The basic idea was to use https://gitlocalize.com, so if you have some time to setup it – feel free.

**Comment by rokr97** [comment]
If I set up a project in gitlocalize then I'll be automatically it's owner but and it'll able to push in my fork only. So the setup should be made by the owners of the original repository.
And to set it up you still have to choose a structure: will it be `tlroadmap/%lang%/skills`, `tlroadmap/skills/%lang%` or 'tlroadmap/translations/%lang%'?

Gitlocalize doesn't support Plant UML files yet. So I can't use it to finish the translation of `roadmap.puml`. 
I want to know where to put the translated files until gitlocalize is set up: just drop them into `translations` folder?

**Comment by etolstoy** [comment]
We discussed this issue with @DevAlloy and decided to temporarily stop all the attempts to translate the roadmap. We plan to finish the content in russian first, and then switch to translating.
