### ISSUE TITLE
Конфликты в .mm файлах

### ISSUE THREAD

**Issue by DevAlloy** [tlbootcamp/tlroadmap#194]
.mm файлы меняются при каждом запуске генерации, что приводит к конфликтам с мастером. Такое происходит даже в случае незначительных изменений в ветке. А решается за счет подливания мастера в свою ветку.

Похоже, что надо подкрутить алгоритм генерации .mm файлов, или их формат(разбиение строк на несколько?).

**Comment by vvscode** [comment]
как на счет не хранить их вообще в репе?

**Comment by etolstoy** [comment]
В репе держать хочется, чтобы красивая png картинка прямо в README на главной была.
