### ISSUE TITLE
Дополнить ветку "Тестирование"

### ISSUE THREAD

**Issue by redfoks** [tlbootcamp/tlroadmap#250]
Предлагаю выделить еще следующие подветки:
- Тест-дизайн - про то, как тестировать, чтобы с большими шансами найти проблему. Сюда же можно про эвристики.
- Тестирование требований - про то, как тестировщики могут улучшить качество требований (и дальнейшее качество разрабатываемого продукта)

Предлагаю также ветку "Unit-тестирование" перенести в "Тестирование", т.к. это не только техническое качество, это и качество продукта тоже. И если мы смотрим в пирамиду тестирования - это один из его уровней.

**Comment by DevAlloy** [comment]
А про тестирование требований это не в сторону Администратора/Получения задач?

**Comment by redfoks** [comment]
> А про тестирование требований это не в сторону Администратора/Получения задач?

И в ту сторону, и в сторону тестирования. Это отдельный процесс, который хорошо проводить при получении задач в команду. Cчитаю, что надо отдельно выделить. По аналогии с code-review в процессе разработки)

**Comment by etolstoy** [comment]
А "тестовую модель" и "тест планы" предлагаешь оставить в таком же виде? Модель не сольется внутрь дизайна?

В целом от меня ок, присылай PR с рефакторингом структуры!

**Comment by redfoks** [comment]
Тест-план предлагаю оставить. Как я это понимаю - это может быть в разных процессах от большого документа по проекту до чек-листа для небольшой фичи.

А вот с тестовой моделью - вопрос. Есть ощущение, что да, сольется внутри тест-дизайна. Часть техник тест-дизайна как раз направлены на создание этой самой модели.

**Comment by b0g3r** [comment]
@redfoks я аккуратно предложу если рефакторить структуру, то уже по новой схеме с папками-подпапками, как в репо https://github.com/b0g3r/tlroadmap, [инструкция](https://tlroadmap.io/contributing.html)

Эти изменения должны приехать в основной репозиторий в ближайшие несколько (2-4) дней, нужно это учесть, чтобы потом лишние гит-конфликты не раскручивать

**Comment by redfoks** [comment]
Спасибо, @b0g3r. Я еще какое-то время над ней подумаю)

**Comment by etolstoy** [comment]
Собственно, изменения уже в мастере, можно смело менять структуру!
