### ISSUE TITLE
Сломаны 2 внешние ссылки

### ISSUE THREAD

**Issue by e13mort** [tlbootcamp/tlroadmap#311]
vuepress-site/roles/product-owner/product-decisions/roadmap-management.html
  *  External link https://www.thisisproductmanagement.com/blog/product-roadmap/ failed: 404 No error

vuepress-site/roles/technical-lead/tech-quality/clean-code.html
  *  External link https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy failed: 404 No error

Обе статьи доступны в закешированном виде
http://webcache.googleusercontent.com/search?q=cache:https://www.thisisproductmanagement.com/blog/product-roadmap/
http://webcache.googleusercontent.com/search?q=cache:https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy

Я не смог найти новые адреса этих статей. Что можно сделать:

- удалить ссылки (быстро)
- поменять ссылки на закешированные версии (информация сохранится, неудобно читать, могут так же пропасть)
- выложить тексты где-то еще (юридический вопрос, можно в виде pdf)

**Comment by etolstoy** [comment]
Спасибо, поправил. Заменил на другие подходящие материалы.
