### ISSUE TITLE
"Стейкхолдеры"

### ISSUE THREAD

**Issue by glader** [tlbootcamp/tlroadmap#317]
Я считаю, что эта транскрибация некорректна, потому что "стейк" - это "steak". А данном случае это "стекхолдеры".

![изображение](https://user-images.githubusercontent.com/494361/85229761-679dac00-b3f4-11ea-8ada-a630ec8c378e.png)

**Comment by b0g3r** [comment]
Понятие закреплено в таком виде в том числе в ГОСТ и профильной литературе

**Comment by b0g3r** [comment]
Транскрипция stake и steak одинакова: `steik`
https://en.m.wiktionary.org/wiki/stake
https://en.m.wiktionary.org/wiki/steak

**Comment by etolstoy** [comment]
Как говорится, даже будь ты хоть тысячу раз прав, какой в этом толк, если гугл плачет.
![](https://i.ibb.co/z5Zw9ss/Screenshot-2020-06-27-at-12-18-14.png)
