### ISSUE TITLE
А почему "снежинка"?

### ISSUE THREAD

**Issue by tigertv** [tlbootcamp/tlroadmap#320]
А почему "тимлид - снежинка"? 
Из поколения "снежинок" или превращается в воду при нагревании?

**Comment by SpiLLeR** [comment]
Думаю, что это отсылка к Максиму Дорофееву и его доклад про людей снежинок)

**Comment by yauhen-info** [comment]
Школа менеджеров Стратоплан тоже использует в контексте менеджер-снежинка, пример [презентации](https://www.slideshare.net/SlavaPankratov/ss-535501). К слову, Дорофеев и Стратоплан точно сотрудничали ранее.

**Comment by DevAlloy** [comment]
@SpiLLeR все так :)
Про суть по-быстрому: https://www.it-agency.ru/academy/jedi-plan/manager-slide.pdf
