### ISSUE TITLE
Site is unavailable

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [tlbootcamp/tlroadmap#345]
Just checked from my local machines - cannot connect to https://tlroadmap.io 

Also, I've checked site availability with different online services - the same result.

Is it expected?

**Comment by b0g3r** [comment]
Sorry for the delay. The problem should be fixed now

**Comment by ZaMaZaN4iK** [comment]
Yeah. Now it works fine.

Thanks a lot!
