### ISSUE TITLE
Мануал по переводу на английский

### ISSUE THREAD

**Issue by SamMolokanov** [tlbootcamp/tlroadmap#359]
Всем привет! Как указано в [FAQ](https://tlroadmap.io/contributing.html#%D0%B7%D0%B0%D1%87%D0%B5%D0%BC-%D0%BA%D0%B0%D0%B6%D0%B4%D1%8B%D0%B9-%D1%80%D0%B0%D0%B7-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-rumd-%D0%B5%D1%81%D0%BB%D0%B8-%D1%8F%D0%B7%D1%8B%D0%BA-%D1%81%D0%B5%D0%B9%D1%87%D0%B0%D1%81-%D0%B2%D1%81%D1%91-%D1%80%D0%B0%D0%B2%D0%BD%D0%BE-%D0%BE%D0%B4%D0%B8%D0%BD) - в планах есть перевод на английский.

Есть ли мануал или документация о том как делать перевод? В идеале пошаговая инструкция вроде:

1. Новая ветка `en-translation-chapterXYZ`
2. Создаем файл `en.md`
3. ...
4. Открыть PR в основной репо с меткой "en translation".

**Comment by DevAlloy** [comment]
@b0g3r @etolstoy сможете по английской версии подсказать?

**Comment by etolstoy** [comment]
Привет! Я планировал найти спонсора, который возьмет на себя оплату профессионального перевода всех веток. Делать это силами сообщества будет очень трудоемко, особенно с учетом необходимости редактуры. Приступим к этому, как только весь русскоязычный контент готов будет.

**Comment by SamMolokanov** [comment]
Спасибо за ответы!
