### ISSUE TITLE
Описать ветку "Обеспечение качества продукта/Тестирование"

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#37]
- Тестовая модель
- Тест-планы
- Пирамида тестирования
- Оптимизация количества тестирования

**Comment by redfoks** [comment]
Беру на себя ветку про пирамиду тестирования.

**Comment by etolstoy** [comment]
В телеграме договорились о том, что пирамиду тестирование сделает Ярослав.
