### ISSUE TITLE
Описать ветку "Автоматизация цикла разработки/CI"

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#49]

**Comment by Real001** [comment]
Беру

**Comment by Real001** [comment]
Мне кажется что в название ветки стоит добавить CI/CD, так как это взаимосвязанные вещи.

**Comment by DevAlloy** [comment]
> Мне кажется что в название ветки стоит добавить CI/CD, так как это взаимосвязанные вещи.

Там соседняя ветка на эту тему, часто для CI/CD используются одна система для автоматизации, но смысл у них все же разный.
