### ISSUE TITLE
Расовая дискриминация на уровне эмоджи

### ISSUE THREAD

**Issue by berlinhipster** [tlbootcamp/tlroadmap#6]
В описании проекта "👩🏼‍💻👨🏻‍💻Карта навыков и модель развития тимлидов" присутствуют только white-skin эмоджи! Ответственно заявляю что это дискриминация! 

Требую добавить следующие эмоджи:
👩🏻‍💻👩‍💻👩🏼‍💻👩🏽‍💻👩🏾‍💻👩🏿‍💻
👨‍💻👨🏻‍💻👨🏼‍💻👨🏽‍💻👨🏾‍💻👨🏿‍💻

**Comment by etolstoy** [comment]
В будущем мы соберем комитет по этике и дайверсити и раз и навсегда решим вопрос инклюзивности выбранных эмодзи – но сейчас в вопросах приоритетов это немного съезжает вниз.

Спасибо за внимательность!
