### ISSUE TITLE
Описать ветку "Развитие себя/Выработка привычек"

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#60]

**Comment by uthunderbird** [comment]
Беру.

**Comment by uthunderbird** [comment]
Предлагаю переименовать в "работу с привычками", поскольку создание и разрушение привычек неразрывно связаны, и многие техники подходят и для первого, и для второго.

**Comment by uthunderbird** [comment]
@etolstoy таск закрыт
