### ISSUE TITLE
Описать ветку "Мышление/Стратегическое видение"

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#65]

**Comment by crazyfrogspb** [comment]
готов взять в работу, в течение пары недель максимум сделаю первую версию

**Comment by crazyfrogspb** [comment]
тут все оказалось значительно сложнее, чем я думал) первая версия готова, но у меня на карандаше еще примерно десять источников, я бы их хотел бы все сначала изучить, если не горит
