### ISSUE TITLE
Дополнить ветку "Найм/Онбординг"

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#77]
Добавить:
- Примеры плохого и хорошего поведения
- Способы прокачки, в том числе практику

**Comment by timmson** [comment]
Забираю

**Comment by timmson** [comment]
Закрываем?

**Comment by drdaemos** [comment]
А можно пошарить пример почти реального чек-листа для онбординга? С него будет проще начать составлять что-то свое.

https://www.notion.so/xcart/Onboarding-checklist-example-0ed0cc85ecc646a7ab4b6f78736a18fa

**Comment by timmson** [comment]
> А можно пошарить пример почти реального чек-листа для онбординга? С него будет проще начать составлять что-то свое.
> 
> https://www.notion.so/xcart/Onboarding-checklist-example-0ed0cc85ecc646a7ab4b6f78736a18fa

Добавил в следующий PR

**Comment by timmson** [comment]
Закрываем?
