### ISSUE TITLE
Дополнить ветку "Управление людьми/Обратная связь"

### ISSUE THREAD

**Issue by etolstoy** [tlbootcamp/tlroadmap#83]
Добавить:
- Примеры плохого и хорошего поведения
- Способы прокачки, в том числе практику

**Comment by timmson** [comment]
Готов взять

**Comment by etolstoy** [comment]
Забирай!

**Comment by timmson** [comment]
@etolstoy, @DevAlloy, подскажите, чем данный раздел должен отличаться от уже существующего - [Обратная связь](https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/feedback.md)? Необходимо сделать фокус на каких-либо аспектах процесса?

**Comment by etolstoy** [comment]
А я же вроде описал в первом сообщении. Тут не хватает двух стандартных для ветки разделов:
- Примеры плохого и хорошего поведения
- Способы прокачки, в том числе практику

**Comment by timmson** [comment]
Закрываем?
